name: publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      #── Docker Hub login ────────────────────────────────────────────────
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}  # <- PAT or password

      # Extract the tag name (v0.1.0 → 0.1.0)
      - name: Extract version
        id: meta
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_OUTPUT"

      #── Build & push multi‑arch image ───────────────────────────────────
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/autonope:${{ steps.meta.outputs.version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/autonope:latest
